stages:
  - build
  - test

cache:
  key: modules
  paths:
    - backend/node_modules
    - frontend/node_modules

build-stage:
  stage: build
  script:
    - echo "Backend Build"
    - (cd backend && npm ci)
    - echo "Frontend Build"
    - (cd frontend && npm ci)
  artifacts:
    paths:
      - backend/node_modules
      - frontend/node_modules

test-stage:
  stage: test
  script:
    - echo "Backend Test"
    - (cd backend && npm test)
    - echo "Frontend Test"
    - (cd frontend && npm test)
  artifacts:
    paths:
      - backend/node_modules
      - frontend/node_modules
